export const UPDATE_CONFIGURATION_SETUP = 'UPDATE_CONFIGURATION_SETUP'
export const CLEAR_CONFIGURATION = 'CLEAR_CONFIGURATION'
export const UPDATE_CONFIGURATION_ITEMS = 'UPDATE_CONFIGURATION_ITEMS'
export const SET_CONFIGURATION_LEGS_TYPE = 'SET_CONFIGURATION_LEGS_TYPE'
export const SET_CONFIGURATION_MODULES_NUMBER = 'SET_CONFIGURATION_MODULES_NUMBER'
export const SET_CONFIGURATION_LEGS_NUMBER = 'SET_CONFIGURATION_LEGS_NUMBER'
export const SET_CONFIGURATION_MODULES_PRICE = 'SET_CONFIGURATION_MODULES_PRICE'
export const SET_CONFIGURATION_LEGS_PRICE = 'SET_CONFIGURATION_LEGS_PRICE'

export const ADD_GROUP_TO_CART = 'ADD_GROUP_TO_CART'
export const REMOVE_GROUP_FROM_CART = 'REMOVE_GROUP_FROM_CART'
export const UPDATE_CART_ITEMS_LIST = 'UPDATE_CART_ITEMS_LIST'
export const EDIT_GROUP_IN_CART = 'EDIT_GROUP_IN_CART'
export const UPDATE_GROUP_IN_CART = 'UPDATE_GROUP_IN_CART'
export const UPDATE_NUMBER_OF_MODULES_IN_CART = 'UPDATE_NUMBER_OF_MODULES_IN_CART'
export const SET_NEW_NUMBER_OF_MODULES_IN_CART = 'SET_NEW_NUMBER_OF_MODULES_IN_CART'
export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL'
export const UPDATE_COUPON_DISCOUNT = 'UPDATE_COUPON_DISCOUNT'
export const SET_COUPON_CODE = 'SET_COUPON_CODE'
export const UPDATE_CART_SHIPPING = 'UPDATE_CART_SHIPPING'
export const UPDATE_CART_DISCOUNT = 'UPDATE_CART_DISCOUNT'
export const SET_STRIPE_ORDER_ID = 'SET_STRIPE_ORDER_ID'
export const TOGGLE_STRIPE_IN_PROGRESS = 'TOGGLE_STRIPE_IN_PROGRESS'
export const EMPTY_CART = 'EMPTY_CART'

export const UPDATE_BILLING_INFO = 'UPDATE_BILLING_INFO'
export const UPDATE_SHIPPING_INFO = 'UPDATE_SHIPPING_INFO'
export const UPDATE_USER_COUNTRY = 'UPDATE_USER_COUNTRY'
export const UPDATE_LATEST_ORDER_ID = 'UPDATE_LATEST_ORDER_ID'



// WEBPACK FOOTER //
// ./src/actions/ActionTypes.js
